echo on fail

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -69,7 +69,7 @@ jobs:
 
             - name: Terraform Plan Status
               if: steps.plan.outcome == 'failure'
-              run: exit 1
+              run: echo "Your Plan Has Failed Sir!" && exit 1
 
             - name: Terraform Apply
               if: github.ref == 'refs/heads/main' && github.event_name == 'push'
